/**
 * PROCESS GAME DATA
 * 
 * Usage: node scripts/process_games_data.js
 * 
 * This script reads the raw 'steam_games_full.jsonl' (generated by the scraper),
 * deduplicates entries, and converts it into a clean 'games.json' file
 * that the frontend can use.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '../src/data');
const INPUT_FILE = path.join(DATA_DIR, 'steam_games_full.jsonl');
const OUTPUT_FILE = path.join(DATA_DIR, 'games.json');

function main() {
  if (!fs.existsSync(INPUT_FILE)) {
    console.error(`Input file not found: ${INPUT_FILE}`);
    console.log("Please run 'node scripts/fetch_all_games.js' first to gather data.");
    return;
  }

  console.log('Reading raw data...');
  const fileContent = fs.readFileSync(INPUT_FILE, 'utf8');
  const lines = fileContent.split('\n').filter(line => line.trim() !== '');

  const gamesMap = new Map();

  lines.forEach((line, index) => {
    try {
      const game = JSON.parse(line);
      // Deduplicate by ID (keep latest)
      gamesMap.set(game.id, game);
    } catch (e) {
      console.warn(`Skipping invalid JSON on line ${index + 1}`);
    }
  });

  const games = Array.from(gamesMap.values());
  console.log(`Total unique games processed: ${games.length}`);

  // Sort by name for now (or maybe ID)
  games.sort((a, b) => a.title.localeCompare(b.title));

  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(games, null, 2));
  console.log(`Successfully wrote ${games.length} games to ${OUTPUT_FILE}`);
}

main();
